name: Python CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Setup python for tox
        uses: actions/setup-python@v4.3.0
        with:
          python-version: 3.9
      - name: install tox
        run: python -m pip install tox
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          miniconda-version: "latest"
          python-version: 3.9
      - uses: actions/checkout@v2.5.0
      - name: Run tox
        run: tox
